version: '3'

services:
  web:
    image: python:3.10
    container_name: django_app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # Monta todo o diretório atual no container
    working_dir: /app  # Define o diretório de trabalho como '/app'
    ports:
      - "8000:8000"  # Mapeia a porta 8000 para o host
    env_file:
      - .env  # Lê as variáveis de ambiente do arquivo .env
    depends_on:
      - db  # Aguarda o serviço do banco de dados
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados do Postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Variáveis de ambiente para o Postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
